# Only runs external services and expose ports
version: "3.3"
services:
  postgresql:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-storage:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672

volumes:
  db-storage: {}