version: "3.3"
services:
  app:
    build: .
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database

  database:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-storage:/var/lib/postgresql/data

  message-proker:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      
volumes:
  db-storage: {}