# Generated by Django 4.1.2 on 2022-12-14 08:49

import apps.order.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('original_text', models.FileField(upload_to=apps.order.models.upload_order_filename)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('type', models.CharField(choices=[('EDIT', 'Edit'), ('TRANSLATION', 'Translation'), ('BOTH', 'Both')], max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='common.language')),
                ('specialized_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.specializedfield')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='common.language')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('STALING', 'Staling')], default='STALING', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedOrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderoffer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('source_language', models.F('target_language')), _negated=True), name="source and target language can't be the same"),
        ),
    ]
