# Generated by Django 4.1.2 on 2022-11-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='specialized_field',
        ),
        migrations.AddField(
            model_name='order',
            name='specialized_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.specializedfield'),
        ),
    ]
