# Generated by Django 4.1.2 on 2022-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_specialized_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INVALID_ORDER', 'invalid order'), ('WAITING_FOR_PAYMENT', 'waiting for payment'), ('WAITING_FOR_ACCEPT', 'waiting for accept')], default='WAITING_FOR_ACCEPT', max_length=20),
        ),
    ]
