# Generated by Django 4.1.2 on 2022-11-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('OPRATOR', 'oprator'), ('EDITOR', 'editor'), ('TRANSLATOR', 'translator'), ('CUSTOMER', 'customer')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('min_charge', models.DecimalField(decimal_places=2, help_text='Minimum charge per word', max_digits=10)),
                ('max_charge', models.DecimalField(decimal_places=2, help_text='Maximum charge per word', max_digits=10)),
                ('max_time', models.PositiveSmallIntegerField(help_text='Maximum time per 5000 word in hour')),
                ('min_time', models.PositiveSmallIntegerField(help_text='Minimum time per 5000 word in hour')),
                ('is_available', models.BooleanField(default=True)),
                ('languages', models.ManyToManyField(related_name='employee_languages', to='account.language')),
                ('specialized_field', models.ManyToManyField(related_name='employee_fields', to='account.specializedfield')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
