# Generated by Django 4.1.2 on 2022-11-26 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_charge', models.DecimalField(decimal_places=2, help_text='Minimum charge per word', max_digits=10)),
                ('max_charge', models.DecimalField(decimal_places=2, help_text='Maximum charge per word', max_digits=10)),
                ('max_time', models.PositiveSmallIntegerField(help_text='Maximum time per 5000 word in hour')),
                ('min_time', models.PositiveSmallIntegerField(help_text='Minimum time per 5000 word in hour')),
                ('is_available', models.BooleanField(default=True)),
                ('languages', models.ManyToManyField(related_name='employee_languages', to='account.language')),
                ('specialized_field', models.ManyToManyField(related_name='employee_fields', to='account.specializedfield')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('min_charge__lt', models.F('max_charge'))), name='min charge should be less than max charge'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('min_time__lt', models.F('max_time'))), name='min time should be less than max time'),
        ),
    ]
