# Generated by Django 4.1.2 on 2022-12-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employee_max_charge_alter_employee_max_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='specialized_field',
            new_name='specialized_fields',
        ),
    ]
