# Generated by Django 4.1.2 on 2022-12-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE_INVOICE', 'Pre-invoice'), ('INVOICE', 'Invoice')], default='PRE_INVOICE', max_length=12)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderoffer')),
            ],
        ),
    ]
