# Generated by Django 4.1.2 on 2022-11-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='suggest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.suggest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PRE_INVOICE', 'Pre-invoice'), ('INVOICE', 'Invoice')], default='PRE_INVOICE', max_length=12),
        ),
    ]
